### ISSUE TITLE
Error en tamaña de imagenes

### ISSUE THREAD

**Issue by mserrano07** [josejesusjj/The-Instagram-Photo-Feed#1]
@josejesusjj El tamaño de las imágenes tiene que ser igual para todo los post

**Comment by josejesusjj** [comment]
Buenas Marcos,

Ya he realizado el cambio que me has solicitado. En todo caso quería
decirte que no he encontrado en ninguna parte de las instrucciones  que el
tamaño deba ser igual para todos los post, y en el gif explicativo las
imágenes no aparecen con el mismo tamaño.

Saludos!
Jose

**Comment by chavisam** [comment]
Ya se ve perfecto, Jose. 
Si quieres.... inserta los iconos del corazón de "Me gusta" de instagram para que lo tengas. Acuérdate que eso lo puedes hacer con Fontawesome
